services:
  - type: web
    name: django-portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Project.wsgi
    staticPublishPath: staticfiles
    autoDeploy: true